In [1]:

import tensorflow as tf
print(tf.version)


<module 'tensorflow._api.v2.version' from 'c:\\Users\\Preethi\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


INTRODUCTION TO TENSORS

https://colab.research.google.com/drive/1F_EWVKa8rbMXi3_fG0w7AtcscFq7Hi7B#forceEdit=true&sandboxMode=true&scrollTo=TAk6QhGUwQRt

In [2]:
string=tf.Variable("this is kishore",tf.string)    #creating tensors
number=tf.Variable(234,tf.int64)
floatingpoint=tf.Variable(2.234,tf.float64)
print(number)
print(string)
print(floatingpoint)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=234>
<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is kishore'>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.234>


In [3]:
#Rank/Degree
rank1 = tf.Variable([12],tf.int64)
rank2 = tf.Variable([['apple'],['orange']],tf.string)
rank3 = tf.Variable([[[12],[23]],[[45],[56]]],tf.int64)
print(tf.rank(string))
print(tf.rank(rank1))
print(tf.rank(rank2))
print(tf.rank(rank3))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [4]:
print(rank1.shape)
print(rank2.shape)
print(rank3.shape)


(1,)
(2, 1)
(2, 2, 1)


In [5]:
tensor1=tf.ones([1,2,3])
tensor2=tf.reshape(tensor1,[2,3,1])
tensor3=tf.reshape(tensor2,[3,-1])
print(tensor1)
print(tensor2)
print(tf.rank(tensor2))
print(tensor3)

# In this case, the product of the dimensions [2, 3, 1] in tensor2 is 2 * 3 * 1 = 6. Since you specified the first dimension as 3 in tensor3,
# TensorFlow infers the size of the second dimension as 6 / 3 = 2. Therefore, the resulting dimensions of tensor3 are [3, 2].

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [6]:
import numpy as np
print(np.__version__)

1.26.4
