In [2]:
import tensorflow as tf


In [3]:
A=[[1,2,3,4,5],
   [6,7,8,9,10],
   [11,12,13,14,15],
   [16,17,18,19,20]]

tensor = tf.Variable(A,tf.int64)


In [4]:
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [5]:
x=tensor[:,2]
v=tensor[::2]  # this is not row column type here we are selecting every row and incrementing it as 2
print(x)
print(v)

tf.Tensor([ 3  8 13 18], shape=(4,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5]
 [11 12 13 14 15]], shape=(2, 5), dtype=int32)
