In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

C:\Users\tmachine\AppData\Local\Temp\ipykernel_12384\3780363213.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
from sklearn.datasets import load_digits
digits = load_digits()

In [3]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [8]:
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [9]:
logi = LogisticRegression()
logi.fit(X_train,y_train)
logi.score(X_test,y_test)

c:\Users\tmachine\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [10]:
support = SVC()
support.fit(X_train,y_train)
support.score(X_test,y_test)

0.9851851851851852

In [11]:
forest = RandomForestClassifier()
forest.fit(X_train,y_train)
forest.score(X_test,y_test)

0.9685185185185186

IN THE ABOVE IF WE RERUN THE TRAIN_TEST_SPLIT() CELL WE GET DIFFERENT SCORE IN EVERY MODEL SO IT IS NOT OPTIMAl SO WE BRING KFOLD ALGORITHM

In [14]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [16]:
for index_train , index_test in kf.split([1,2,3,4,5,6,7,8,9]):
    print(index_train,index_test)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


STRATIFIED KFOLD IS JUST SIMILAR TO KFOLD BUT IT IS SLIGHTLY BETTER IN SPLITTING , IT WILL DIVIDE EACH OF THE CATEGORIES IN A UNIFOM WAY

In [17]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [18]:
from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits=3)

In [25]:
score_l = []
score_svm = []
score_rf = []

for train_index , test_index in kf.split(digits.data):
    X_train , X_test , y_train , y_test = digits.data[train_index] , digits.data[test_index], \
                                          digits.target[train_index] , digits.target[test_index]
    
    score_l.append(get_score(LogisticRegression(),X_train , X_test , y_train , y_test))
    score_svm.append(get_score(SVC(),X_train , X_test , y_train , y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train , X_test , y_train , y_test))

c:\Users\tmachine\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\tmachine\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.or

In [26]:
score_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [27]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [28]:
score_rf

[0.9315525876460768, 0.9432387312186978, 0.9248747913188647]

NOW WE ARE GOING TO OVERCOME THIS HARD CODE PARD WHAT WE HAVE DONE ABOVE LIKE DEFING A FUNCTION AND CALLING IT IN A FOR LOOP SO TO OVERCOME THIS WE ARE GOING TO USE THE CROSS_VAL_SCORE

In [29]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target)

c:\Users\tmachine\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\tmachine\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.or

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [30]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [31]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.92777778, 0.88888889, 0.94428969, 0.96100279, 0.91086351])