## Artificial Neural Networks

### Importing the dataset

In [204]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [205]:
tf.__version__

'2.15.1'

In [206]:
dataset = pd.read_csv("E:\T-Machine\python\Churn_Modelling.csv")


In [207]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [208]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [209]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [210]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

## Encoding Categorical Data

#### Label encodding the Gender column

In [211]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [212]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

### One Hot encoding the "Geograpy" column

In [213]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [214]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into Trainig set and Testing set

In [215]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [216]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 12)
(2000, 12)
(8000,)
(2000,)


## Feature Scaling
##### Whenever you are creating a Artificial Neural Network it is necessary to do a feature scaling it is fundamental

In [217]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building the ANN

#### Initializing the ANN

In [218]:
ann = tf.keras.models.Sequential()

#### Adding the input layer and the first hidden layer

In [219]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Adding the second hidden layer

In [220]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#### Adding the output layer

In [221]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training the ANN

##### compiling the ANN

In [222]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#### Training the ANN on the Training set

In [223]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100


250/250 [==============================] - 1s 825us/step - loss: 0.6612 - accuracy: 0.6459
Epoch 2/100
250/250 [==============================] - 0s 800us/step - loss: 0.4818 - accuracy: 0.8114
Epoch 3/100
250/250 [==============================] - 0s 702us/step - loss: 0.4459 - accuracy: 0.8177
Epoch 4/100
250/250 [==============================] - 0s 731us/step - loss: 0.4333 - accuracy: 0.8204
Epoch 5/100
250/250 [==============================] - 0s 738us/step - loss: 0.4265 - accuracy: 0.8219
Epoch 6/100
250/250 [==============================] - 0s 730us/step - loss: 0.4209 - accuracy: 0.8264
Epoch 7/100
250/250 [==============================] - 0s 757us/step - loss: 0.4158 - accuracy: 0.8274
Epoch 8/100
250/250 [==============================] - 0s 768us/step - loss: 0.4113 - accuracy: 0.8311
Epoch 9/100
250/250 [==============================] - 0s 705us/step - loss: 0.4065 - accuracy: 0.8325
Epoch 10/100
250/250 [==============================] - 0s 753us/step - loss: 0.4008 

# Making the prediction and evaluating the model

#### Predicting the result of a single observation

###### Use our ANN model to predict if the customer with the following information will leave the bank:
###### Geography:France
###### Credit Score:600
###### Gender:Male
###### Age:40 years old
###### Tenure:3years
###### Balance:$60000
###### Number of Products:2
###### Does this customer have a credit card? Yes
###### Is this customer have a credict card? Yes
###### Estimated Salary:$50000
###### So,should we say goodbye to that customer

In [224]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5
# y_predict = ann.predict([[1,0,0,600,1,40,3,60000,2,1,1,50000]])
# print(y_predict)
# print("THE PREDICTED VALUE IS : ",np.argmax(y_predict[0]))

1/1 [==============================] - 0s 45ms/step


array([[False]])

#### Predicting the test results

In [228]:
y_predict = ann.predict(X_test)
y_predict = (y_predict>0.5)
# print(np.concatenate((y_predict.reshape(len(y_predict),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 610us/step


In [229]:
ann.evaluate(X_test,y_test)

63/63 [==============================] - 0s 724us/step - loss: 0.3344 - accuracy: 0.8585


[0.33443811535835266, 0.8585000038146973]

#### Making the confusion Matrix

In [230]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm = confusion_matrix(y_test,y_predict)
print(cm)
accuracy_score(y_test,y_predict)


[[1512   83]
 [ 200  205]]


0.8585