In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.datasets import load_wine

In [3]:
df = load_wine()

In [4]:
dir(df)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [5]:
df.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [7]:
df.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [9]:
Data = pd.DataFrame(df.data,columns=df.feature_names)
Data.head(20)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0     14.23        1.71  2.43               15.6      127.0           2.80   
1     13.20        1.78  2.14               11.2      100.0           2.65   
2     13.16        2.36  2.67               18.6      101.0           2.80   
3     14.37        1.95  2.50               16.8      113.0           3.85   
4     13.24        2.59  2.87               21.0      118.0           2.80   
5     14.20        1.76  2.45               15.2      112.0           3.27   
6     14.39        1.87  2.45               14.6       96.0           2.50   
7     14.06        2.15  2.61               17.6      121.0           2.60   
8     14.83        1.64  2.17               14.0       97.0           2.80   
9     13.86        1.35  2.27               16.0       98.0           2.98   
10    14.10        2.16  2.30               18.0      105.0           2.95   
11    14.12        1.48  2.32               16.8       95.0           2.20   
12    13.75        1.73  2.41               16.0       89.0           2.60   
13    14.75        1.73  2.39               11.4       91.0           3.10   
14    14.38        1.87  2.38               12.0      102.0           3.30   
15    13.63        1.81  2.70               17.2      112.0           2.85   
16    14.30        1.92  2.72               20.0      120.0           2.80   
17    13.83        1.57  2.62               20.0      115.0           2.95   
18    14.19        1.59  2.48               16.5      108.0           3.30   
19    13.64        3.10  2.56               15.2      116.0           2.70   

    flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0         3.06                  0.28             2.29             5.64  1.04   
1         2.76                  0.26             1.28             4.38  1.05   
2         3.24                  0.30             2.81             5.68  1.03   
3         3.49                  0.24             2.18             7.80  0.86   
4         2.69                  0.39             1.82             4.32  1.04   
5         3.39                  0.34             1.97             6.75  1.05   
6         2.52                  0.30             1.98             5.25  1.02   
7         2.51                  0.31             1.25             5.05  1.06   
8         2.98                  0.29             1.98             5.20  1.08   
9         3.15                  0.22             1.85             7.22  1.01   
10        3.32                  0.22             2.38             5.75  1.25   
11        2.43                  0.26             1.57             5.00  1.17   
12        2.76                  0.29             1.81             5.60  1.15   
13        3.69                  0.43             2.81             5.40  1.25   
14        3.64                  0.29             2.96             7.50  1.20   
15        2.91                  0.30             1.46             7.30  1.28   
16        3.14                  0.33             1.97             6.20  1.07   
17        3.40                  0.40             1.72             6.60  1.13   
18        3.93                  0.32             1.86             8.70  1.23   
19        3.03                  0.17             1.66             5.10  0.96   

    od280/od315_of_diluted_wines  proline  
0                           3.92   1065.0  
1                           3.40   1050.0  
2                           3.17   1185.0  
3                           3.45   1480.0  
4                           2.93    735.0  
5                           2.85   1450.0  
6                           3.58   1290.0  
7                           3.58   1295.0  
8                           2.85   1045.0  
9                           3.55   1045.0  
10                          3.17   1510.0  
11                          2.82   1280.0  
12                          2.90   1320.0  
13                          2.73   1150.0  
14                      

In [10]:
df.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [11]:
df.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [12]:
Data['target'] = df.target
Data.head(10)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   
5    14.20        1.76  2.45               15.2      112.0           3.27   
6    14.39        1.87  2.45               14.6       96.0           2.50   
7    14.06        2.15  2.61               17.6      121.0           2.60   
8    14.83        1.64  2.17               14.0       97.0           2.80   
9    13.86        1.35  2.27               16.0       98.0           2.98   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   
5        3.39                  0.34             1.97             6.75  1.05   
6        2.52                  0.30             1.98             5.25  1.02   
7        2.51                  0.31             1.25             5.05  1.06   
8        2.98                  0.29             1.98             5.20  1.08   
9        3.15                  0.22             1.85             7.22  1.01   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0  
5                          2.85   1450.0       0  
6                          3.58   1290.0       0  
7                          3.58   1295.0       0  
8                          2.85   1045.0       0  
9                          3.55   1045.0       0

In [16]:
X=Data.values[:,0:13]
y=Data.values[:,13]

In [17]:
print(X.shape)
print(y.shape)

(178, 13)
(178,)


In [18]:
df.data.shape

(178, 13)

In [19]:
df.target.shape

(178,)

In [20]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2)

In [21]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(142, 13)
(36, 13)
(142,)
(36,)


In [22]:
G = GaussianNB()
G.fit(X_train,y_train)


GaussianNB()

In [23]:
G.predict(X_test)

array([1., 0., 2., 2., 1., 0., 1., 2., 1., 1., 2., 0., 1., 1., 0., 2., 2.,
       2., 2., 2., 1., 1., 0., 1., 1., 0., 1., 2., 2., 1., 1., 2., 1., 2.,
       1., 0.])

In [24]:
y_test[0:10]

array([1., 0., 2., 1., 1., 0., 1., 2., 1., 1.])

In [25]:
G.score(X_test,y_test)

0.9444444444444444

In [26]:
M = MultinomialNB()
M.fit(X_train,y_train)


MultinomialNB()

In [27]:
M.score(X_test,y_test)

0.8333333333333334